version: '3.7'

services:
  lafs-web:
    container_name: lafs-web
    restart: always 
    build: .
    ports:
      - 4200:4200
    environment:
      NODE_ENV: production

networks:
  default:
    external:
      name: lafs-net
